### ISSUE TITLE
dismiss error

### ISSUE THREAD

**Issue by badboy-tian** [dylanwuzh/flutter_progress_dialog#2]
```
Unhandled Exception: NoSuchMethodError: The method 'showDismissAnim' was called on null.
Receiver: null
Tried calling: showDismissAnim()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ProgressFuture.dismiss (package:flutter_progress_dialog/src/core/future.dart:25:34)
#2      ProgressManager.dismissAll.<anonymous closure>
```

**Comment by salvador-moreno** [comment]
This happens to me as well when showProgressDialog() and dismissProgressDialog() are called too close in time. Putting it into a Future.delayed serves as a workaround, however, it is not a propper solution.

`Future.delayed(const Duration(milliseconds: 1000), () {dismissProgressDialog();});`

**Comment by Sandeepbandral** [comment]
Its been a few hours that I stuck in this issue, your answer work like a charm. thanks!
